#!/usr/bin/env php
<?php

// Fix for hosts that do not have date.timezone set
date_default_timezone_set('UTC');

// if you don't want to setup permissions the proper way, just uncomment the following PHP line
//umask(0000);

if (function_exists('set_time_limit')) {
    set_time_limit(0);
}

defined('IN_ALERTS_CONSOLE') or define('IN_ALERTS_CONSOLE', 1);

define('ALERTS_ROOT_DIR', realpath(__DIR__));

require_once __DIR__.'/class/user.class.php';
require_once __DIR__.'/class/alert.class.php';
require_once __DIR__.'/mautic/config/BasicAuth.php';
require_once __DIR__.'/mautic/class/contact.class.php';

if ($argc > 1) {
    if ($argv[1] == 'init') {
        $time_start = microtime(true);

        // Recuperar lista de contatos do Mautic
        $contacts = new Contacts;
        $my_vhl_contacts = $contacts->listContacts('my_vhl_user:1 send_alert:1', 0, 1);
        $my_vhl_contacts = $contacts->listContacts('my_vhl_user:1 send_alert:1', 0, $my_vhl_contacts['total']);

        // Normalizar lista de contatos do Mautic
        if ( $my_vhl_contacts['total'] > 0 ) {
            print("[Mautic] Normalizando contatos...\n");

            $ids = array_keys($my_vhl_contacts['contacts']);

            foreach ($ids as $i) {
                $data = array( 'send_alert' => FALSE );
                $contact = $contacts->editContact($i, $data);
            }

            print("[Mautic] Total de contatos: " . $my_vhl_contacts['total'] . "\n");
            print("--------------------------------------------------\n");
        }

        // Recuperar usuários da Minha BVS
        $users = new Users;
        $active_users = $users->get_users(TRUE, TRUE, TRUE);

        print("[Minha BVS] Total de usuários ativos: " . count($active_users) . "\n");

        // Atualizar lista de contatos do Mautic
        if ( count($active_users) > 0 ) {
            print("[Minha BVS] Checando usuários válidos...\n");

            $valid_users = array();

            // Checar quais usuários são válidos
            foreach ($active_users as $user) {
                $obj = new Alerts();
                $is_valid = $obj->is_valid($user);

                if ( $is_valid ) {
                    $valid_users[] = $user;
                }
            }

            print("[Minha BVS] Total de usuários válidos: " . count($valid_users) . "\n");

            if ( $valid_users ) {
                print("--------------------------------------------------\n");
                print("[Mautic] Atualizando lista de contatos...\n");

                foreach ($valid_users as $vu) {
                    $alerts_lang = getAlertsLanguage($vu['country']);
                    $contact = $contacts->listContacts('my_vhl_user:1 email:'.$vu['email'], 0, 1);

                    if ( $contact['total'] == 1 ) {
                        $id = key($contact['contacts']);
                        $data = array( 'send_alert' => TRUE, 'my_vhl_id' => $vu['my_vhl_id'], 'alerts_lang' => $alerts_lang );
                        $contact = $contacts->editContact($id, $data);
                    } else {
                        $vu['alerts_lang'] = $alerts_lang;
                        $vu['country'] = $countries[$vu['country']]['en'];
                        $contact = $contacts->createContact($vu, TRUE);
                    }
                }

                $total_contacts = $contacts->listContacts('my_vhl_user:1 send_alert:1', 0, 1);

                print("[Mautic] Total de contatos: " . $total_contacts['total'] . "\n");
            }
        }

        $time_end = microtime(true);
        //$time = date("H:i:s",$time_end-$time_start);
        $time = date("H\hi\ms\s",$time_end-$time_start);

        echo "\nTempo de execução: $time\n";
    }
}