#!/bin/bash

export MAUTICPATH=`pwd`

if [ "$1" = "segments" ]; then
    if [ "$2" = "update" ]; then
        php ${MAUTICPATH}/console mautic:segments:update --no-interaction --no-ansi -f --env=prod
    fi
elif [ "$1" = "campaigns" ]; then
    if [ "$2" = "rebuild" ]; then
        php ${MAUTICPATH}/console mautic:campaigns:rebuild --campaign-id=${3} -f --env=prod
    elif [ "$2" = "trigger" ]; then
        php ${MAUTICPATH}/console mautic:campaigns:trigger --campaign-id=${3} -f --env=prod
    fi
fi
